CREATE TABLE DATA_MART.CROM (
    IDX INT AUTO_INCREMENT PRIMARY KEY,
    FILE_NAME VARCHAR(255),
    IMG MEDIUMBLOB,
    P_DATE TIMESTAMP,
    DW_DATE TIMESTAMP, 
    DM_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),

    DEFECT_FLAG TINYINT(1), -- 불량 여부 (0: 정상, 1: 불량)
    DEFECT_TYPE VARCHAR(50), -- 불량 유형 (예: 스크래치, 오염 등)
    MODEL_CONFIDENCE FLOAT -- AI 판별 신뢰도 (예: 0.92)
);
