CREATE TABLE DATA_MART.CROM (
    IDX INT AUTO_INCREMENT PRIMARY KEY,
    FILE_NAME VARCHAR(255),
    IMG MEDIUMBLOB,
    P_DATE TIMESTAMP,
    DW_DATE TIMESTAMP, 
    DM_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),

    DEFECT_FLAG TINYINT(1), 
    DEFECT_TYPE VARCHAR(50),
    MODEL_CONFIDENCE FLOAT
);